# Netlify build configuration
[build]
  base = "thokMarket"          # ЁЯСИ рдпрд╣ рддреБрдореНрд╣рд╛рд░реЗ frontend folder рдХрд╛ рд╕рд╣реА рдирд╛рдо рд╣реИ
  publish = "thokMarket/dist"  # ЁЯСИ Vite рдХрд╛ build output folder
  command = "npm run build"    # ЁЯСИ Build command

# Optional: Specify Node.js version (recommended for consistency)
[build.environment]
  NODE_VERSION = "18"

# Optional: Redirect all routes to index.html (for React Router support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
